const CATEGORIES=["Casa & Estrutura","Produção","Credenciamento","Segurança","Open Bar","Open Food","Banheiros & Limpeza","Som & DJ","Shows & Artistas","Telão & Técnica","Decoração","Espaços Instagramáveis","Foto & Vídeo","Influenciadores","VIP BLACK","Patrocinadores & Ativações","Experiências","Queima de Fogos","Marketing","Compras de Produção","Desmontagem & Pós-evento","Outros"];
const uid=()=>crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2)+Date.now().toString(36);
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:2}).format(Number(v||0));
const pct=v=>`${Number(v||0).toLocaleString('pt-BR',{maximumFractionDigits:1})}%`;
const n=v=>Number(v||0);
const today=()=>new Date().toISOString();
const seedExpenses=[
["Casa & Estrutura","Locação Casa Villa Zenia"],["Casa & Estrutura","Caução / depósito de segurança"],["Casa & Estrutura","Taxa de limpeza da casa"],["Casa & Estrutura","Horas extras de montagem/desmontagem"],["Casa & Estrutura","Mobiliário adicional"],["Casa & Estrutura","Gerador de energia backup"],["Casa & Estrutura","Combustível do gerador"],["Casa & Estrutura","Extensões e réguas elétricas"],["Casa & Estrutura","Proteção de cabos"],["Casa & Estrutura","Plano B de chuva / cobertura"],["Casa & Estrutura","Ventilação / climatização extra"],["Casa & Estrutura","Valet / estacionamento"],
["Produção","Produtor executivo"],["Produção","Coordenador geral no dia"],["Produção","Produtor de backstage"],["Produção","Produtor de artistas"],["Produção","Produtor de patrocinadores"],["Produção","Assistentes / runners"],["Produção","Rádios comunicadores"],["Produção","Alimentação da equipe"],["Produção","Água da equipe"],["Produção","Transporte / estacionamento da equipe"],["Produção","Crachás / uniformes da equipe"],
["Credenciamento","Recepcionistas / hostesses"],["Credenciamento","Mesa / balcão de recepção"],["Credenciamento","Pulseiras público geral"],["Credenciamento","Pulseiras influenciadores"],["Credenciamento","Pulseiras VIP BLACK"],["Credenciamento","Credenciais produção"],["Credenciamento","Leitor QR / celular / tablet"],["Credenciamento","Internet de apoio na entrada"],["Credenciamento","Placas e sinalização"],
["Segurança","Seguranças do evento"],["Segurança","Segurança VIP BLACK"],["Segurança","Brigadista"],["Segurança","Primeiros socorros / kit"],["Segurança","Ambulância / apoio médico"],["Segurança","Extintores / conferência"],["Segurança","Iluminação de emergência"],
["Open Bar","Água sem gás"],["Open Bar","Água com gás"],["Open Bar","Refrigerante normal"],["Open Bar","Refrigerante zero"],["Open Bar","Suco natural"],["Open Bar","Chopp"],["Open Bar","Chopeira / CO₂"],["Open Bar","Vodka"],["Open Bar","Gin"],["Open Bar","Bases para drinks"],["Open Bar","Água tônica"],["Open Bar","Xaropes / açúcar / adoçante"],["Open Bar","Frutas / limão / hortelã / guarnições"],["Open Bar","Gelo para bebidas"],["Open Bar","Gelo para conservação"],["Open Bar","Caixas térmicas / baldes de gelo"],["Open Bar","Copos / taças"],["Open Bar","Guardanapos de bar"],["Open Bar","Utensílios de bar"],["Open Bar","Bartenders"],["Open Bar","Barbacks / apoio de bar"],["Open Bar","Tapetes antiderrapantes / panos"],
["Open Food","Canapés"],["Open Food","Patês e acompanhamentos"],["Open Food","Mini-hambúrgueres"],["Open Food","Finger foods premium"],["Open Food","Opções vegetarianas"],["Open Food","Doces / sobremesas"],["Open Food","Louças / descartáveis premium"],["Open Food","Talheres / guardanapos"],["Open Food","Bandejas / utensílios"],["Open Food","Refrigeração e conservação"],["Open Food","Equipe de cozinha"],["Open Food","Garçons"],["Open Food","Transporte do buffet"],
["Banheiros & Limpeza","Equipe de limpeza durante o evento"],["Banheiros & Limpeza","Limpeza pré-evento"],["Banheiros & Limpeza","Limpeza pós-evento"],["Banheiros & Limpeza","Papel higiênico"],["Banheiros & Limpeza","Papel toalha"],["Banheiros & Limpeza","Sabonete líquido"],["Banheiros & Limpeza","Álcool em gel"],["Banheiros & Limpeza","Aromatizador"],["Banheiros & Limpeza","Desinfetante / produtos de limpeza"],["Banheiros & Limpeza","Sacos de lixo pequenos"],["Banheiros & Limpeza","Sacos de lixo grandes reforçados"],["Banheiros & Limpeza","Luvas / panos / mop / baldes"],["Banheiros & Limpeza","Kit absorventes femininos"],["Banheiros & Limpeza","Desentupidor / kit emergência banheiro"],
["Som & DJ","DJ"],["Som & DJ","Sistema de som"],["Som & DJ","Subwoofers / monitores"],["Som & DJ","Mesa de som"],["Som & DJ","Microfones sem fio"],["Som & DJ","Microfone reserva"],["Som & DJ","Técnico de som"],["Som & DJ","Passagem de som"],["Som & DJ","Cabos / adaptadores / pedestais"],["Som & DJ","Playlist / notebook de backup"],
["Shows & Artistas","Cachê Salim Saleme"],["Shows & Artistas","Segundo cantor"],["Shows & Artistas","Transporte artistas"],["Shows & Artistas","Camarim"],["Shows & Artistas","Rider técnico / backline"],["Shows & Artistas","Roadie / equipe de apoio"],["Shows & Artistas","Alimentação e bebidas artistas"],["Shows & Artistas","ECAD / direitos de execução musical"],
["Telão & Técnica","Painel de LED"],["Telão & Técnica","Estrutura / suporte LED"],["Telão & Técnica","Operador de LED"],["Telão & Técnica","Player / notebook"],["Telão & Técnica","Conteúdo / motion do telão"],
["Decoração","Projeto de decoração premium"],["Decoração","Flores / plantas"],["Decoração","Iluminação decorativa"],["Decoração","Velas / luminárias"],["Decoração","Lounges / bistrôs / mesas"],["Decoração","Identidade visual / placas"],["Decoração","Montagem / desmontagem decoração"],["Decoração","Frete decoração"],
["Espaços Instagramáveis","Espaço instagramável 1"],["Espaços Instagramáveis","Espaço instagramável 2"],["Espaços Instagramáveis","Iluminação dedicada para conteúdo"],["Espaços Instagramáveis","Neon / LED / branding"],
["Foto & Vídeo","Fotógrafos"],["Foto & Vídeo","Videomakers"],["Foto & Vídeo","Reel maker / conteúdo vertical"],["Foto & Vídeo","Aftermovie"],["Foto & Vídeo","Drone / autorizações"],["Foto & Vídeo","Iluminação para entrevistas"],["Foto & Vídeo","Microfones de lapela"],["Foto & Vídeo","SSD / backup de mídia"],["Foto & Vídeo","Edição e entrega final"],
["Influenciadores","Convites / kits para influenciadores"],["Influenciadores","Recepção dedicada"],["Influenciadores","Controle de acompanhantes"],["Influenciadores","Estrutura palestras 5–10 min"],["Influenciadores","Material de divulgação individual"],["Influenciadores","Brindes / presentes influenciadores"],
["VIP BLACK","Mobiliário VIP BLACK"],["VIP BLACK","Decoração VIP BLACK"],["VIP BLACK","Garçom dedicado VIP"],["VIP BLACK","Sinalização / acesso VIP"],["VIP BLACK","Bebidas diferenciadas VIP"],
["Patrocinadores & Ativações","Backdrop de patrocinadores"],["Patrocinadores & Ativações","Estruturas de ativação"],["Patrocinadores & Ativações","Promotores de marca"],["Patrocinadores & Ativações","Sampling / brindes patrocinadores"],["Patrocinadores & Ativações","Relatório pós-evento patrocinadores"],
["Experiências","Cuspidor de fogo"],["Experiências","2 dançarinas"],["Experiências","Figurino performers"],["Experiências","Camarim performers"],["Experiências","Segurança / isolamento performance"],
["Queima de Fogos","Empresa de pirotecnia"],["Queima de Fogos","Autorizações / documentação"],["Queima de Fogos","Operador e montagem"],["Queima de Fogos","Área de segurança / proteção"],["Queima de Fogos","Limpeza pós-fogos"],
["Marketing","Identidade visual"],["Marketing","Flyers / teasers"],["Marketing","Vídeo oficial"],["Marketing","Landing page / página de vendas"],["Marketing","Tráfego pago"],["Marketing","Assessoria de imprensa"],["Marketing","Kit mídia para influenciadores"],
["Compras de Produção","Silver tape / fita crepe / dupla face"],["Compras de Produção","Abraçadeiras / enforca-gato"],["Compras de Produção","Tesoura / estilete / canetas"],["Compras de Produção","Pilhas / baterias"],["Compras de Produção","Power banks / carregadores"],["Compras de Produção","Lanternas"],["Compras de Produção","Kit ferramentas"],["Compras de Produção","Guarda-chuvas"],["Compras de Produção","Repelente / protetor solar equipe"],["Compras de Produção","Kit costura / figurino"],["Compras de Produção","Caixas organizadoras"],
["Desmontagem & Pós-evento","Fretes de desmontagem"],["Desmontagem & Pós-evento","Retirada de lixo"],["Desmontagem & Pós-evento","Prestação de contas"],["Desmontagem & Pós-evento","Achados e perdidos"],["Desmontagem & Pós-evento","Entrega relatório final"],
];
function makeExpense([category,name]){return{id:uid(),category,name,qty:1,estimate:0,actual:0,paid:0,status:"Planejado",priority:"Normal",owner:"",supplier:"",contact:"",due:"",details:"",notes:"",included:true,createdAt:today(),updatedAt:today()}}
function defaultState(){return{version:1,meta:{createdAt:today(),updatedAt:today(),lastEditor:""},settings:{eventName:"CONNECT CLUB",venue:"Casa Villa Zenia • Joá • Rio de Janeiro",editor:"",contingencyPct:10,commissionPct:20,affiliateSharePct:100,platformFeePct:0,paymentFeePct:0,taxPct:0},expenses:seedExpenses.map(makeExpense),tickets:[{id:uid(),name:"1º lote",price:500,capacity:30,sold:0},{id:uid(),name:"2º lote",price:700,capacity:40,sold:0},{id:uid(),name:"3º lote",price:1000,capacity:30,sold:0}],revenues:[{id:uid(),name:"Patrocínios",expected:0,confirmed:0,status:"Prospectando",notes:""}],activity:[]}}
let state=defaultState();
let remoteUrl=new URL(location.href).searchParams.get('db')||'';let saveTimer=null;let isLoadingRemote=false;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function log(action,detail){state.activity.unshift({id:uid(),at:today(),by:state.settings.editor||'Equipe',action,detail});state.activity=state.activity.slice(0,200)}
function bestUnit(e){return n(e.actual)>0?n(e.actual):n(e.estimate)}
function bestTotal(e){return e.included&&e.status!=="Cancelado"?n(e.qty)*bestUnit(e):0}
function contractedTotal(e){return e.included&&e.status!=="Cancelado"&&n(e.actual)>0?n(e.qty)*n(e.actual):0}
function calc(){
 const active=state.expenses.filter(e=>e.included&&e.status!=="Cancelado");
 const base=active.reduce((s,e)=>s+bestTotal(e),0);const contingency=base*n(state.settings.contingencyPct)/100;const budget=base+contingency;
 const contracted=active.reduce((s,e)=>s+contractedTotal(e),0);const paid=active.reduce((s,e)=>s+n(e.paid),0);const payable=Math.max(0,contracted-paid);
 const ticketPotential=state.tickets.reduce((s,l)=>s+n(l.price)*n(l.capacity),0);const ticketCurrent=state.tickets.reduce((s,l)=>s+n(l.price)*Math.min(n(l.sold),n(l.capacity)),0);
 const extraExpected=state.revenues.reduce((s,r)=>s+(n(r.confirmed)>0?n(r.confirmed):n(r.expected)),0);const extraConfirmed=state.revenues.reduce((s,r)=>s+n(r.confirmed),0);
 const varRate=(n(state.settings.platformFeePct)+n(state.settings.paymentFeePct)+n(state.settings.taxPct)+n(state.settings.commissionPct)*n(state.settings.affiliateSharePct)/100)/100;
 const feesPotential=ticketPotential*varRate;const revenuePotential=ticketPotential+extraExpected;const profit=revenuePotential-budget-feesPotential;
 const feesCurrent=ticketCurrent*varRate;const currentNet=ticketCurrent+extraConfirmed-feesCurrent-paid;
 let remaining=Math.max(0,budget-extraConfirmed),beTickets=0,beGross=0,beNet=0,beLot='—';
 outer:for(const lot of state.tickets){for(let i=0;i<n(lot.capacity);i++){const gross=n(lot.price),net=gross*(1-varRate);beTickets++;beGross+=gross;beNet+=net;remaining-=net;beLot=lot.name;if(remaining<=0)break outer;}}
